# manually triggered script to build and deploy the web version to github pages
name: Deploy Web Demo
on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install 3.1.60
          ./emsdk activate 3.1.60
          cd ..
      - name: build
        run: |
          mkdir build
          cd build
          cmake --preset emscripten-release ..
          cmake --build .
          mv Nesnausk_CrankTheWorld.html index.html
          mkdir web
          cp *.wasm *.html *.js web
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage
          path: build/web
          retention-days: 1

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: setup-pages
        uses: actions/configure-pages@v5
      - name: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: webpage
      - name: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: deploy-gh-pages
        id: deployment
        uses: actions/deploy-pages@v4
